### PR TITLE
fix: handle hardware back button in React Native

### LINKED ISSUE #84: Fix hardware back button behaviour on Android
Now, when use opens "New Zone" screen and tries to navigate back on Android, it'll close the whole "Shipping Zone" screen (they'll go back to "Settings" screen).

The expected behaviour is that they'll navigate back to the list of Shipping Zones

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #84 

## Description
This PR fixes the behaviour of Android back hardware button to expected one (see videos).

### Before
https://github.com/woocommerce/WooCommerce-Shared/assets/5845095/b842ccb3-e446-43b9-983e-078ff5dd6809

### After
https://github.com/woocommerce/WooCommerce-Shared/assets/5845095/6b9106d7-075b-49ef-9a06-b4d3a56fb56f

### CODE REVIEW

File: AddShippingZone.tsx [hunk 1]
```diff
@@ -25,8 +26,20 @@ const AddShippingZone = () => {
...
         }),
     });
+    BackHandler.addEventListener("hardwareBackPress", handleBackButtonClick);
+    return () => {
+      BackHandler.removeEventListener(
+        "hardwareBackPress",
+        handleBackButtonClick
+      );
+    };
   }, [navigation]);
```
Comment (Ecarrion) [inline AddShippingZone.tsx:36]: This does not seem to have any effect on iOS, which is good! But I wonder, do we have to add this handle on each new screen?

**Review by Ecarrion — APPROVED** [review]
